version: '3.8'

services:
  nextjs:
    build:
      context: ./conolizing-the-see
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - FLASK_API_URL=http://localhost:5000

  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge