version: '3.8'
services:
  nextjs:
    build:
      context: ./conolizing-the-see
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network
    environment:
      - FLASK_API_URL=http://flask:5000
    volumes:
      - ./conolizing-the-see:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - flask

  flask:
    build:
      context: ./api
      dockerfile: Dockerfile
    networks:
      - app-network
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
    environment:
      - FLASK_RUN_HOST=0.0.0.0

networks:
  app-network:
    driver: bridge